services:
  api:
    build:
      context: .
      dockerfile: ApiServer/Dockerfile
    image: game-server-api:latest
    container_name: api-server
    env_file:
      - .env
    ports:
      - "50000:5251"
    networks:
      - gameserver-net
    environment:
    - JWT_SECRET_KEY
    - MYSQL_CONNECTION_STRING
    ulimits:
      nofile:
        soft: 2048
        hard: 4096
    restart : always
    
  tcp:
    build:
      context: .
      dockerfile: TcpServer/Dockerfile
    image: game-server-tcp:latest  
    container_name: tcp-server
    env_file:
      - .env
    ports:
      - "50001:7777"
    networks:
      - gameserver-net
    environment:
      - JWT_SECRET_KEY
      - MYSQL_CONNECTION_STRING
    depends_on:
      - api
    ulimits:
      nofile:
        soft: 2048
        hard: 4096
    restart : always
    
networks:
  gameserver-net:
    driver: bridge