name: Deploy to EC2

on:
  push:
    branches: [ master ]

jobs:
  deploy:
    name: Deploy to EC2
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Setup SSH key
      run: |
        echo "${{ secrets.EC2_KEY }}" > ci_key
        chmod 600 ci_key

    - name: Deploy to EC2
      run: |
        ssh -o StrictHostKeyChecking=no -i ci_key ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} << 'EOF'
          cd GameServerSolution
          git pull origin main
          docker compose build
          docker compose up -d
        EOF